title: Leesangwon blog
description: Leesangwon blog
author: leesangwon0114
github: http://leesangwon0114.github.io
about: I am software developer. Currently working in Nexon, focused in Python and C++.
disqus_shortname: stackproblems
google_analytics: G-WLF3GLY2TV
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/sangwon.lee.58760"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/%EC%83%81%EC%9B%90-%EC%9D%B4-55660b101/"
    - icon: fa-github
      link: "https://github.com/leesangwon0114"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: Category
      url: /category/codecomplete
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/

url: "http://leesangwon0114.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

# Analytics
analytics:
  provider               : "google-gtag" 
  google:
    tracking_id          : "G-WLF3GLY2TV"
    anonymize_ip         : # true, false (default)
